version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hg-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db-hg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hg-network

networks:
  hg-network:

volumes:
  postgres_data:
